<<<<<<< HEAD
theme: jekyll-theme-hacker
title: Bienvenid@ a mis trabajos de Infovis!
description: Estos trabajos son para la materia Visualización de la Información en el ITBA.
||||||| b3b216c
=======
theme: jekyll-theme-hacker
>>>>>>> f38b2731884ac3bc4e1c4efc966d45c811631148
